#!/usr/bin/env python

import sys

from gps_com_node.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'gps_com_node'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
