#!/usr/bin/env python

import sys

from gps_com_node_v2.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'gps_com_node_v2'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
