#!/usr/bin/env python

import sys

from directional_antenna_system.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'directional_antenna_system'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
