#!/usr/bin/env python

import sys

from osm_maps_node.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'osm_maps_node'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
